import React, { useCallback, useEffect, useRef, useState } from "react";
import { apiUrl } from "@/lib/api";

// Mobile-first slider/puzzle captcha.
//
// - Big touch target, no hover affordances, works on a 360 px-wide phone.
// - Submits the absolute slot position (in track px) plus a series of
//   {t, x} motion samples the server uses for sanity-checking that the
//   drag was generated by a human and not a script.
// - Renders the server-issued background and piece images as plain <img>
//   tags from the data-URLs the server sent.

interface ChallengePayload {
  challengeId: string;
  backgroundImageDataUrl: string;
  pieceImageDataUrl: string;
  pieceY: number;
  pieceSize: number;
  trackHeight: number;
  trackWidth: number;
}

interface MotionSample {
  t: number;
  x: number;
}

export interface SliderCaptchaProps {
  walletAddress: string;
  onPass: () => void;
  onCancel?: () => void;
}

type Status =
  | { kind: "loading" }
  | { kind: "ready"; challenge: ChallengePayload }
  | { kind: "verifying" }
  | { kind: "passed" }
  | { kind: "failed"; message: string }
  | { kind: "cooldown"; message: string };

export function SliderCaptcha(props: SliderCaptchaProps): React.ReactElement {
  const { walletAddress, onPass, onCancel } = props;
  const [status, setStatus] = useState<Status>({ kind: "loading" });
  const [pieceX, setPieceX] = useState(0);
  const samplesRef = useRef<MotionSample[]>([]);
  const draggingRef = useRef(false);
  const startXRef = useRef(0);
  const startTimeRef = useRef(0);
  const trackRef = useRef<HTMLDivElement | null>(null);

  const loadChallenge = useCallback(async () => {
    setStatus({ kind: "loading" });
    setPieceX(0);
    samplesRef.current = [];
    try {
      const res = await fetch(apiUrl("/api/captcha/challenge"), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ walletAddress }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.status === 429) {
        setStatus({
          kind: "cooldown",
          message:
            data?.message || "Too many tries — please wait and try again.",
        });
        return;
      }
      if (!res.ok) {
        setStatus({
          kind: "failed",
          message: data?.message || `Could not load verification (${res.status}).`,
        });
        return;
      }
      if (data?.alreadyVerified) {
        setStatus({ kind: "passed" });
        onPass();
        return;
      }
      setStatus({ kind: "ready", challenge: data as ChallengePayload });
    } catch (e: any) {
      setStatus({
        kind: "failed",
        message: e?.message || "Network error loading verification.",
      });
    }
  }, [walletAddress, onPass]);

  useEffect(() => {
    void loadChallenge();
  }, [loadChallenge]);

  const onPointerDown = (e: React.PointerEvent<HTMLDivElement>) => {
    if (status.kind !== "ready") return;
    (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);
    draggingRef.current = true;
    startXRef.current = e.clientX - pieceX;
    startTimeRef.current = performance.now();
    samplesRef.current = [{ t: 0, x: pieceX }];
  };

  const clampX = (x: number, challenge: ChallengePayload) => {
    const max = challenge.trackWidth - challenge.pieceSize;
    if (x < 0) return 0;
    if (x > max) return max;
    return x;
  };

  const onPointerMove = (e: React.PointerEvent<HTMLDivElement>) => {
    if (!draggingRef.current || status.kind !== "ready") return;
    const x = clampX(e.clientX - startXRef.current, status.challenge);
    setPieceX(x);
    samplesRef.current.push({
      t: performance.now() - startTimeRef.current,
      x,
    });
  };

  const submit = useCallback(
    async (challenge: ChallengePayload, finalX: number) => {
      setStatus({ kind: "verifying" });
      try {
        const res = await fetch(apiUrl("/api/captcha/verify"), {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            challengeId: challenge.challengeId,
            slotX: finalX,
            motionSamples: samplesRef.current,
          }),
        });
        const data = await res.json().catch(() => ({}));
        if (res.ok && data?.ok) {
          setStatus({ kind: "passed" });
          onPass();
          return;
        }
        if (res.status === 429) {
          setStatus({
            kind: "cooldown",
            message:
              data?.message || "Too many tries — please wait and try again.",
          });
          return;
        }
        setStatus({
          kind: "failed",
          message: data?.message || "Verification failed. Please try again.",
        });
      } catch (e: any) {
        setStatus({
          kind: "failed",
          message: e?.message || "Network error during verification.",
        });
      }
    },
    [onPass]
  );

  const onPointerUp = (e: React.PointerEvent<HTMLDivElement>) => {
    if (!draggingRef.current || status.kind !== "ready") return;
    draggingRef.current = false;
    try {
      (e.currentTarget as HTMLDivElement).releasePointerCapture(e.pointerId);
    } catch {
      /* non-fatal */
    }
    const finalX = pieceX;
    void submit(status.challenge, finalX);
  };

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.7)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 16,
        zIndex: 9999,
        // Respect iOS safe-area insets so the modal isn't clipped under
        // the home-indicator on phones that use 100vh quirks.
        paddingBottom: "max(16px, env(safe-area-inset-bottom))",
      }}
      data-testid="slider-captcha-modal"
    >
      <div
        style={{
          background: "#1a1f2c",
          borderRadius: 16,
          padding: 16,
          width: "100%",
          maxWidth: 320,
          color: "#fff",
          boxShadow: "0 8px 32px rgba(0,0,0,0.6)",
        }}
      >
        <h3 style={{ margin: "0 0 8px", fontSize: 18, fontWeight: 600 }}>
          Verify it's you
        </h3>
        <p style={{ margin: "0 0 12px", fontSize: 13, opacity: 0.85 }}>
          Slide the piece into the empty spot.
        </p>

        {status.kind === "loading" && (
          <div style={{ padding: 24, textAlign: "center" }}>Loading…</div>
        )}

        {status.kind === "verifying" && (
          <div style={{ padding: 24, textAlign: "center" }}>Checking…</div>
        )}

        {status.kind === "ready" && (
          <>
            <div
              ref={trackRef}
              style={{
                position: "relative",
                width: status.challenge.trackWidth,
                height: status.challenge.trackHeight,
                maxWidth: "100%",
                margin: "0 auto",
                borderRadius: 8,
                overflow: "hidden",
                touchAction: "none",
              }}
            >
              <img
                src={status.challenge.backgroundImageDataUrl}
                alt=""
                draggable={false}
                style={{
                  width: "100%",
                  height: "100%",
                  display: "block",
                  pointerEvents: "none",
                  userSelect: "none",
                }}
              />
              <img
                src={status.challenge.pieceImageDataUrl}
                alt="puzzle piece"
                draggable={false}
                style={{
                  position: "absolute",
                  top: status.challenge.pieceY,
                  left: pieceX,
                  width: status.challenge.pieceSize,
                  height: status.challenge.pieceSize,
                  pointerEvents: "none",
                  userSelect: "none",
                  filter: "drop-shadow(0 2px 4px rgba(0,0,0,0.5))",
                }}
              />
            </div>

            {/* Drag track — large, thumb-friendly. */}
            <div
              role="slider"
              aria-label="Slide to verify"
              tabIndex={0}
              onPointerDown={onPointerDown}
              onPointerMove={onPointerMove}
              onPointerUp={onPointerUp}
              onPointerCancel={onPointerUp}
              data-testid="slider-captcha-track"
              style={{
                marginTop: 12,
                height: 56,
                borderRadius: 28,
                background: "rgba(255,255,255,0.08)",
                position: "relative",
                touchAction: "none",
                cursor: "grab",
              }}
            >
              <div
                style={{
                  position: "absolute",
                  inset: 0,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  pointerEvents: "none",
                  fontSize: 13,
                  opacity: 0.7,
                }}
              >
                Slide right →
              </div>
              <div
                style={{
                  position: "absolute",
                  top: 4,
                  left: pieceX *
                    ((status.challenge.trackWidth - 48) /
                      Math.max(1, status.challenge.trackWidth - status.challenge.pieceSize)),
                  width: 48,
                  height: 48,
                  borderRadius: "50%",
                  background: "#3b82f6",
                  pointerEvents: "none",
                }}
              />
            </div>
          </>
        )}

        {status.kind === "passed" && (
          <div style={{ padding: 16, textAlign: "center", color: "#4ade80" }}>
            Verified ✓
          </div>
        )}

        {status.kind === "failed" && (
          <div style={{ padding: 16, textAlign: "center" }}>
            <p style={{ color: "#fca5a5", margin: "0 0 12px" }}>
              {status.message}
            </p>
            <button
              type="button"
              onClick={() => void loadChallenge()}
              data-testid="slider-captcha-retry"
              style={{
                background: "#3b82f6",
                color: "#fff",
                border: 0,
                borderRadius: 12,
                padding: "12px 20px",
                fontSize: 15,
                fontWeight: 600,
                minHeight: 44,
              }}
            >
              Try again
            </button>
          </div>
        )}

        {status.kind === "cooldown" && (
          <div
            style={{ padding: 16, textAlign: "center", color: "#fbbf24" }}
          >
            {status.message}
          </div>
        )}

        {onCancel && (
          <div style={{ marginTop: 12, textAlign: "center" }}>
            <button
              type="button"
              onClick={onCancel}
              style={{
                background: "transparent",
                color: "#94a3b8",
                border: 0,
                fontSize: 13,
                padding: "8px 12px",
                minHeight: 36,
              }}
            >
              Cancel
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export default SliderCaptcha;
